variable "display_name" {
  type        = string
  description = "Subscription display name."
  nullable    = false

  validation {
    condition     = length(var.display_name) >= 1 && length(var.display_name) <= 100
    error_message = "display_name must be between 1 and 100 characters."
  }
}

variable "name" {
  type        = string
  description = "The name (subscription identifier) of the API Management subscription."
  nullable    = false

  validation {
    condition     = length(var.name) >= 1 && length(var.name) <= 256 && can(regex("^[^*#&+:<>?]+$", var.name))
    error_message = "name must be 1 to 256 characters and cannot contain `*`, `#`, `&`, `+`, `:`, `<`, `>`, or `?`."
  }
}

variable "parent_id" {
  type        = string
  description = "The fully-qualified ARM resource ID of the existing API Management service that will contain the subscription."
  nullable    = false

  validation {
    condition     = can(provider::azapi::parse_resource_id("Microsoft.ApiManagement/service", var.parent_id))
    error_message = "`parent_id` must be a valid Microsoft.ApiManagement/service resource ID."
  }
}

variable "scope" {
  type        = string
  description = "ARM scope for the subscription, e.g. `/products/{productId}`, `/apis/{apiId}`, or `/apis`."
  nullable    = false

  validation {
    condition     = trimspace(var.scope) != ""
    error_message = "scope must not be empty."
  }
}

variable "allow_tracing" {
  type        = bool
  default     = null
  description = "Whether tracing can be enabled for this subscription."
}

variable "enable_telemetry" {
  type        = bool
  default     = true
  description = <<DESCRIPTION
This variable controls whether or not telemetry is enabled for the module.
For more information see <https://aka.ms/avm/telemetryinfo>.
If it is set to false, then no telemetry will be collected.
DESCRIPTION
  nullable    = false
}

variable "ignore_body_changes" {
  type = object({
    apimanagement_service_subscriptions = optional(list(string), [])
  })
  default     = {}
  description = <<DESCRIPTION
Body-relative paths ignored on the subscription resource. Paths use dot notation.
Changes take effect only after apply. Ignored configuration is not sent to Azure.

- `apimanagement_service_subscriptions` - Paths ignored on the subscription resource.
DESCRIPTION
  nullable    = false
}

variable "owner_id" {
  type        = string
  default     = null
  description = "User path for whom the subscription is created, in the form `/users/{userId}`."
}

variable "primary_key" {
  type        = string
  default     = null
  description = "Primary subscription key. Generated by Azure when omitted."
  sensitive   = true

  validation {
    condition     = var.primary_key == null || (length(var.primary_key) >= 1 && length(var.primary_key) <= 256)
    error_message = "primary_key must be between 1 and 256 characters when set."
  }
}

variable "resource_types" {
  type = object({
    apimanagement_service_subscriptions = optional(string, "Microsoft.ApiManagement/service/subscriptions@2024-05-01")
  })
  default     = {}
  description = <<DESCRIPTION
AzAPI resource types and API versions used by the subscription submodule.

- `apimanagement_service_subscriptions` - Resource type and API version for the subscription.
DESCRIPTION
  nullable    = false
}

variable "retry" {
  type = object({
    error_message_regex  = optional(list(string), null)
    interval_seconds     = optional(number, null)
    max_interval_seconds = optional(number, null)
    multiplier           = optional(number, null)
    randomization_factor = optional(number, null)
  })
  default     = null
  description = "Retry configuration for AzAPI resources. See AzAPI provider `retry` documentation."
}

variable "secondary_key" {
  type        = string
  default     = null
  description = "Secondary subscription key. Generated by Azure when omitted."
  sensitive   = true

  validation {
    condition     = var.secondary_key == null || (length(var.secondary_key) >= 1 && length(var.secondary_key) <= 256)
    error_message = "secondary_key must be between 1 and 256 characters when set."
  }
}

variable "state" {
  type        = string
  default     = null
  description = "Initial subscription state. Possible values: `active`, `suspended`, `submitted`, `rejected`, `cancelled`, `expired`."

  validation {
    condition     = var.state == null || contains(["active", "cancelled", "expired", "rejected", "submitted", "suspended"], var.state)
    error_message = "state must be one of: active, cancelled, expired, rejected, submitted, suspended."
  }
}

variable "timeouts" {
  type = object({
    create = optional(string)
    read   = optional(string)
    update = optional(string)
    delete = optional(string)
  })
  default     = null
  description = "Timeouts for AzAPI resources."
}
